#!/usr/bin/env bash

# Directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias rm='rm -I --preserve-root'

# Editor
alias c='code .'

# File management
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias pcat='pygmentize -g'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -alhF'
alias la='ls -A'
alias l='ls -CF'

# System Management
alias up='yay -Syu --noconfirm --noansweredit --sudoloop'
alias upup='yay -Syu --noconfirm --noansweredit --devel --sudoloop'
alias pastebin='curl -F c=@- https://ptpb.pw'

# Add an "alert" alias for long running commands. Use like so:
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Taskwarrior
alias tn='task add'
alias t='task'
alias tl='task list'
alias ts='task sync'

# Tmux
alias mux='tmux attach -t david || tmux new -s david'

# Docker
alias drmsc='docker rm $(docker ps -a -q)'
alias drmdi='docker rmi $(docker images -f dangling=true -q)'
alias dj='docker run -p 8888:8888 -it --rm davidgasquez/dopyter:latest'
alias djlo='docker run -p 8888:8888 -it --user $(id -u):$(id -g) --rm -v $PWD:/work davidgasquez/dopyter:latest'

# Custom
alias handbook='code ~/projects/handbook/content'
