#!/usr/bin/env bash

# Get folder or file size in disk
function fs() {
	if du -b /dev/null > /dev/null 2>&1; then
		local arg=-sbh;
	else
		local arg=-sh;
	fi
	if [[ -n "$@" ]]; then
		du $arg -- "$@";
	else
		du $arg .[^.]* ./*;
	fi;
}

# Make new directory and move to it
function md {
    mkdir -p "$@" && cd $_;
}

# Open the current directory, otherwise open the given folder (argument)
function o() {
	if [ $# -eq 0 ]; then
		xdg-open .;
	else
		xdg-open "$@";
	fi;
}

# Check the weather from the command line
function weather() {
    IFS=+ curl "http://wttr.in/$*"
}

# Get help from the command line. Help Me With...
function hmw()
{
  where="$1"; shift
  IFS=+ curl "https://cht.sh/$where/$*"
}
