#!/usr/bin/env bash

# Local binaries
export PATH="$PATH:/home/$(whoami)/.local/bin"

# Steam
export STEAM_FRAME_FORCE_CLOSE=1
export STEAM_RUNTIME=0

# Go
export GOPATH=$HOME/.go
export PATH=$PATH:$GOPATH/bin
