# History
export HISTSIZE=100000
export HISTFILE="$HOME/.history"
export SAVEHIST=$HISTSIZE

# Completion
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
autoload -Uz compinit
compinit

# Colors
autoload -U colors
colors

# Auto cd
setopt auto_cd

# Editor
export EDITOR='nano'

# Antigen
source "$HOME/.antigen/antigen/antigen.zsh"

# Bundles
antigen bundles <<EOBUNDLES
    git
    pip
    taskwarrior
    zsh-users/zsh-history-substring-search
    zsh-users/zsh-completions
EOBUNDLES

# Theme
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

# Apply
antigen apply

# History Search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Keyboard shorcuts
bindkey ";5C" forward-word
bindkey ";5D" backward-word
bindkey "\e[3~" delete-char
bindkey "^[[3;3~" delete-word
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line

# Load the shell dotfiles:
for file in ~/.{aliases,functions,localrc}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;

# Export environmental variables
export $(cat ~/.env | xargs)
