extensions:
  computercontroller:
    enabled: true
    name: computercontroller
    type: builtin
  developer:
    enabled: true
    name: developer
    type: builtin
  memory:
    enabled: true
    name: memory
    type: builtin
GOOSE_PROVIDER: google
GOOSE_MODEL: gemini-2.5-pro-exp-03-25
