GOOSE_MODE: auto
extensions:
  computercontroller:
    enabled: true
    name: computercontroller
    type: builtin
  developer:
    enabled: true
    name: developer
    type: builtin
  memory:
    enabled: false
    name: memory
    type: builtin
GOOSE_CLI_MIN_PRIORITY: 0.2
GOOSE_PROVIDER: google
GOOSE_PLANNER_PROVIDER: google
GOOSE_MODEL: gemini-2.5-flash-preview-05-20
GOOSE_PLANNER_MODEL: gemini-2.5-flash-preview-04-17-thinking
