$blue = rgb(8caaee)
$green = rgb(a6d189)
$red = rgb(e78284)
$redAlpha = e78284
$text = rgb(c6d0f5)
$overlay0Alpha = 737994
$surface0 = rgb(414559)

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.15
    outer_color = $blue
    inner_color = $surface0
    font_color = $text
    fade_on_empty = false
    placeholder_text = <span foreground="##$overlay0Alpha">Enter Password...</span>
    rounding = 15
    check_color = $green
    fail_color = $red
    fail_text = <span foreground="##$redAlpha">$FAIL</span>

    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = $text
    font_size = 70
    font_family = JetBrains Mono

    position = 0, 120
    halign = center
    valign = center
}
