# Minimal MangoHud layout

legacy_layout=0
hud_compact

fps
frametime
gamemode

position=top-right
font_size=12
background_alpha=0.35
round_corners=0

toggle_hud=Shift_R+F12

# Catppuccin Frappe
text_color=C6D0F5
background_color=303446
fps_color=A6D189
frametime_color=81C8BE
