#!/usr/bin/env bash
set -euo pipefail

# Check if URL argument is provided
if [ -z "$1" ]; then
  echo "Usage: yt2srt <youtube-url>"
  exit 1
fi

url="$1"

# Fetch subtitles and process them
yt-dlp -q --skip-download --write-auto-subs --sub-format ttml "$url"
