[[colors.indexed_colors]]
color = "#EF9F76"
index = 16

[[colors.indexed_colors]]
color = "#F2D5CF"
index = 17

[colors.bright]
black = "#626880"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#F4B8E4"
red = "#E78284"
white = "#A5ADCE"
yellow = "#E5C890"

[colors.cursor]
cursor = "#F2D5CF"
text = "#303446"

[colors.dim]
black = "#51576D"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#F4B8E4"
red = "#E78284"
white = "#B5BFE2"
yellow = "#E5C890"

[colors.hints.end]
background = "#A5ADCE"
foreground = "#303446"

[colors.hints.start]
background = "#E5C890"
foreground = "#303446"

[colors.normal]
black = "#51576D"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#F4B8E4"
red = "#E78284"
white = "#B5BFE2"
yellow = "#E5C890"

[colors.primary]
background = "#303446"
bright_foreground = "#C6D0F5"
dim_foreground = "#C6D0F5"
foreground = "#C6D0F5"

[colors.search.focused_match]
background = "#A6D189"
foreground = "#303446"

[colors.search.matches]
background = "#A5ADCE"
foreground = "#303446"

[colors.selection]
background = "#F2D5CF"
text = "#303446"

[colors.vi_mode_cursor]
cursor = "#BABBF1"
text = "#303446"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 20000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = false

[window.padding]
x = 15
y = 10
