# Bash

# shellcheck shell=bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Starship
eval "$(starship init bash)"

# History
export HISTSIZE=50000
export HISTFILESIZE=50000
export HISTCONTROL=ignoreboth:erasedups
export HISTIGNORE="ls:ll:cd:pwd:exit:clear"

# Shell options
shopt -s checkwinsize
shopt -s globstar

# Modern navigation
shopt -s autocd cdspell dirspell

# Better completion
shopt -s no_empty_cmd_completion direxpand

# Enhanced history
shopt -s histappend cmdhist lithist

# FZF
eval "$(fzf --bash)"

# Zoxide
eval "$(zoxide init bash)"

# PATH
export PATH="$HOME/projects/dotfiles/scripts:$HOME/.local/bin:$PATH"

# Shared shell config
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/shared.sh"
