# ZSH

# PATH
export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$HOME/projects/dotfiles/scripts:$PATH

# History
HISTFILE=~/.histfile
HISTSIZE=50000
SAVEHIST=50000

# Avoid % in prompt
set +o prompt_cr +o prompt_sp

# Shelldon
eval "$(sheldon -q --non-interactive source)"

# Starship
eval "$(starship init zsh)"

# Options
setopt autocd
setopt extended_glob
setopt hist_ignore_all_dups
setopt hist_expire_dups_first
setopt hist_verify
setopt extended_history
setopt hist_reduce_blanks
setopt inc_append_history
setopt share_history
setopt correct
setopt auto_menu

# Bindkeys
bindkey -e

# Completions
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
zstyle :compinstall filename '/home/david/.zshrc'
zstyle ':completion:*' menu select

# Initialize Completions
# Smarter completion initialization
autoload -Uz compinit
if [[ -f ~/.zcompdump && ~/.zcompdump -nt /usr/share/zsh ]] && [[ ! ~/.zcompdump -ot /usr/local/share/zsh ]]; then
  compinit -C -u
else
  compinit -u
fi

# Aliases
alias cd='z'
alias ls='eza --color=auto --icons=always'
alias ll='eza -l --icons'
alias la='eza -la --icons'
alias tree='eza --tree --icons'
alias cat='bat -pp'
alias up='paru -Syu --devel --skipreview'
alias tn='tod task create -p Personal -u Today -l "" --priority 1 -c'
alias tnw='tod task create -p Work -u Today -l "" --priority 1 -c'
alias tls='tod list view -f "Today"'
alias chat='llm chat'
alias cmd='llm -t cmd'
alias copy='wl-copy'
alias pasta='wl-paste'

# Functions
aigcm() {
  cat ~/projects/dotfiles/codex/prompts/commit.md | codex exec -
  # git add -A .
  # git diff --minimal --cached | \
  #   llm -t gitcommit > $(git rev-parse --git-dir)/COMMIT_EDITMSG && \
  #   git commit --verbose --edit --file=$(git rev-parse --git-dir)/COMMIT_EDITMSG
}

qgs() {
  git pull &&
  git add -A . &&
  git cm "⚡" &&
  git push
}

# Quick Query YouTube
qq-yt() {
  if [[ $# -lt 2 ]]; then
    echo "Usage: qq-yt <youtube-url> <prompt>" >&2
    return 1
  fi

  local url="$1"
  shift
  local prompt="$*"

  llm -m gemini-3-pro-preview -a "$url" "$prompt"
}

subdl() {
  uvx subliminal download -l es -s "$1"
}

# FZF
source <(fzf --zsh)

# Zoxide
eval "$(zoxide init zsh)"

# Load .env files
load_dotenv() {
  [[ -f .env ]] || return
  [[ -O .env ]] || { echo "Warning: .env not owned by you"; return 1; }
  setopt local_options allexport
  source .env
}
autoload -U add-zsh-hook
add-zsh-hook chpwd load_dotenv
load_dotenv

# Move cursor
bindkey "^[[1;5C" forward-word
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word
bindkey "^[[1;5D" backward-word

# Supr delete
bindkey "^[[3~" delete-char

# History substring search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='bg=blue,fg=black,bold'

# Hyprland
if [[ -z "$WAYLAND_DISPLAY" ]] && [[ "$(tty)" == /dev/tty* ]]; then
	if uwsm check may-start; then
		exec uwsm start default
	fi
fi
