# ZSH

# PATH
export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$HOME/projects/dotfiles/scripts:$PATH

# History
HISTFILE=~/.histfile
HISTSIZE=50000
SAVEHIST=50000

# Avoid % in prompt
set +o prompt_cr +o prompt_sp

# Shelldon
eval "$(sheldon -q --non-interactive source)"

# Starship
eval "$(starship init zsh)"

# Options
setopt autocd
setopt extended_glob
setopt hist_ignore_all_dups
setopt hist_expire_dups_first
setopt hist_verify
setopt extended_history
setopt hist_reduce_blanks
setopt inc_append_history
setopt share_history
setopt correct
setopt auto_menu

# Bindkeys
bindkey -e

# Completions
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
zstyle :compinstall filename '/home/david/.zshrc'
zstyle ':completion:*' menu select

# Initialize Completions
# Smarter completion initialization
autoload -Uz compinit
if [[ -f ~/.zcompdump && ~/.zcompdump -nt /usr/share/zsh ]] && [[ ! ~/.zcompdump -ot /usr/local/share/zsh ]]; then
  compinit -C -u
else
  compinit -u
fi

# Aliases
alias cd='z'
alias ls='eza --color=auto --icons=always'
alias ll='eza -l --icons'
alias la='eza -la --icons'
alias tree='eza --tree --icons'
alias cat='bat -pp'
alias up='paru -Syu --devel --skipreview && (uv tool upgrade --all & npm update -g & pull-all-dirs ~/projects & npx skills update & wait)'
alias tn='td task add --project "Personal" --due "today" --priority p1'
alias tnw='td task add --project "Work" --due "today" --priority p1'
alias tls='td today'
alias copy='wl-copy'
alias pasta='wl-paste'

open() {
  xdg-open "$@" >/dev/null 2>&1
}

qgs() {
  git pull &&
  git add -A . &&
  git cm "⚡" &&
  git push
}

subdl() {
  uvx subliminal download -l es -s "$1"
}

# FZF
source <(fzf --zsh)

# Zoxide
eval "$(zoxide init zsh)"

# Load .env files
load_dotenv() {
  [[ -f .env ]] || return
  [[ -O .env ]] || { echo "Warning: .env not owned by you"; return 1; }
  setopt local_options allexport
  source .env
}
autoload -U add-zsh-hook
add-zsh-hook chpwd load_dotenv
load_dotenv

# Move cursor
bindkey "^[[1;5C" forward-word
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word
bindkey "^[[1;5D" backward-word

# Supr delete
bindkey "^[[3~" delete-char

# History substring search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='bg=blue,fg=black,bold'

# Hyprland
if [[ -z "$WAYLAND_DISPLAY" ]] && [[ "$(tty)" == /dev/tty* ]]; then
	if uwsm check may-start; then
		exec uwsm start default
	fi
fi
