#!/usr/bin/env bash

# Directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias rm='rm -I --preserve-root'

# File management
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -alhF'
alias la='ls -A'
alias l='ls -CF'

# Update system
alias up='pacaur -Syu --noconfirm --noedit'
alias upup='pacaur -Syu --noconfirm --noedit --devel'

# Add an "alert" alias for long running commands. Use like so:
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Taskwarrior
alias tn='task add'
alias t='task'
alias tl='task list'
alias ts='task sync'

# Fuck
alias fuck='eval $(thefuck $(fc -ln -1)); history -r'

# Tmux
alias mux='tmux attach -t david || tmux new -s david'
