#!/usr/bin/env bash

# Directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias rm='rm -I --preserve-root'

function md {
    mkdir -p "$@" && cd $_;
}

# File management
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Update system
alias up='sudo apt-get update && sudo apt-get -y upgrade'

# Add an "alert" alias for long running commands. Use like so:
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Taskwarrior
alias tn='task add'
alias t='task'
alias tl='task list'
alias ts='task sync'

# Fuck
alias fuck='eval $(thefuck $(fc -ln -1)); history -r'
